remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme

# theme: jekyll-theme-minimal
title: K酱的GitHub页面主页
description: 欲言又止，不知所措
show_excerpts: true
google_analytics: UA-NNNNNNNN-N
minima:
  skin: dark
header_pages:
  - about.md
  - portfolio.md
#kramdown:
# math_engine: mathjax


# http://haixing-hu.github.io/programming/2013/09/20/how-to-use-mathjax-in-jekyll-generated-github-pages/
# https://math.stackexchange.com/editing-help
# https://github.com/mathjax/MathJax
# https://www.mathjax.org/
# https://stackoverflow.com/questions/26275645/how-to-support-latex-in-github-pages/72383929#72383929
# https://stackoverflow.com/questions/26275645/how-to-support-latex-in-github-pages
# https://kramdown.gettalong.org/converter/html.html#math-support
